
import sys, os, abc

from .Platform import Platform

""" 
        @authors:
            Alejandro Balderrama
            Nadia Karichev
            Hector Cervantes
        @description
            This class is a subclass of platform. This class will implement the submission platform. 
    """

class Submission(Platform):
    # fill the values here for your specific platform
    platform_name = "submission"
    platform_start_command = " "
    platform_end_command = " "
    platform_version = " "
    platformInstallation = " "
    port = " "
    ip = " "
    link = "submission.com"
    # the fields below will be generated by Platform Manager
    processID = 0
    platform_id = " "
    subplatforms = {" ", " "}

    #returns link to connect to website
    def getLink(self):
        return self.link 
    #returns ip and port to connect to website
    def getIpPort(self):
        return self.ip + ":" + self.port
    #returns platform name
    def getPlatformName(self):
        return self.platform_name
    
    #returns where the platforms installation path
    def getPlatformInstallation(self):
        return self.platformInstallation
    
    #return the version of the platform 
    def getPlatformVersion(self):
        return self.platform_version
    
    #return a platformID. You can pick a random value for this field.
    def getPlatformID(self):
        return int(self.platform_id)
    # return command that starts platform
    def get_start_command(self):
        return self.platform_start_command + " -a " + self.ip + " -p " + self.port 

    #returns command to stop platform
    def get_stop_command(self):
        return self.platform_end_command + str(self.processID + 1)
    
    # returns list of subplatforms
    def get_sub_platforms(self):
        return self.subplatforms
    
    def requestHandler(self, jsonObject):
        print("Handling Request")
    
    
    #add more methods below if you need to do more tasks
platform = Submission()
print(platform.get_start_command())


